
package grafica;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.Sistema;
import logica.Vacuna;
import logica.Vacuna.TipoVacuna;
import static logica.Vacuna.TipoVacuna.SINOVAC;


public class EnviarVacunas extends javax.swing.JFrame {

           
    public EnviarVacunas() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        dispose();
        this.setLocationRelativeTo(null);
        Sistema sistema= Sistema.getInstance();
        tbeTablaVacunas.setModel(sistema.tablaVacunas());
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(sistema.tablaVacunas());
        tbeTablaVacunas.setRowSorter(sorter);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        lblSeleccionVacunatorio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        listaVacunatorios = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbeTablaVacunas = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 430));
        setPreferredSize(new java.awt.Dimension(620, 430));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        lblSeleccionVacunatorio.setText("Seleccione Vacunatorio:");
        getContentPane().add(lblSeleccionVacunatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        lblCantidad.setText("Cantidad:");
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        listaVacunatorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro", "Cordón", "Ciudad Vieja", "Aguada", "Tres Cruces", "Pocitos", "La Blanqueada" }));
        listaVacunatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVacunatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(listaVacunatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 127, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 127, -1));

        tbeTablaVacunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbeTablaVacunas.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tbeTablaVacunasComponentAdded(evt);
            }
        });
        jScrollPane2.setViewportView(tbeTablaVacunas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 460, 160));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        int filaSeleccionada = tbeTablaVacunas.getSelectedRow();
        String tipo = (String) tbeTablaVacunas.getValueAt(filaSeleccionada,1);
        TipoVacuna tipoVacuna=null;
        switch(tipo){
            case "Sinovac": tipoVacuna=tipoVacuna.SINOVAC; break;
            case "Pfizer": tipoVacuna=tipoVacuna.PFIZER; break;
            case "Astrazeneca": tipoVacuna=tipoVacuna.ASTRAZENECA; break;
        }
        int idVacuna = Integer.parseInt(tbeTablaVacunas.getValueAt(filaSeleccionada, 0).toString());
        int dosisDisponibles = Integer.parseInt(tbeTablaVacunas.getValueAt(filaSeleccionada, 2).toString()); 
        String fechaVencimiento = (String) tbeTablaVacunas.getValueAt(filaSeleccionada, 3);
        String laboratorio = (String) tbeTablaVacunas.getValueAt(filaSeleccionada, 4);
        
        Vacuna vacuna=new Vacuna(idVacuna, tipoVacuna, fechaVencimiento, dosisDisponibles, laboratorio);
        
        int nombreVacunatorio= listaVacunatorios.getSelectedIndex();
        String vacunatorio = null;
        switch(nombreVacunatorio){
            case 0: vacunatorio = "Centro"; break;
            case 1: vacunatorio = "Cordón"; break;
            case 2: vacunatorio = "Ciudad Vieja"; break;
            case 3: vacunatorio = "Aguada"; break;
            case 4: vacunatorio = "Tres Cruces"; break;
            case 5: vacunatorio = "Pocitos"; break;
            case 6: vacunatorio = "La Blanqueada"; break;
        }
        int cantidadDosisEnviar=Integer.parseInt(txtCantidad.getText());
        if (!txtCantidad.getText().trim().equalsIgnoreCase("")){
            if(dosisDisponibles>=cantidadDosisEnviar && cantidadDosisEnviar>0){
                try {
                    Sistema.getInstance().enviarVacunas(vacuna, cantidadDosisEnviar, vacunatorio);
                } catch (Exception ex) {
                    Logger.getLogger(EnviarVacunas.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this,"Se envio correctamente");
            } 
        }
        txtCantidad.setText("");
        try {
            Sistema sistema= Sistema.getInstance();
            tbeTablaVacunas.setModel(Sistema.getInstance().tablaVacunas());
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(sistema.tablaVacunas());
            tbeTablaVacunas.setRowSorter(sorter);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EnviarVacunas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EnviarVacunas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EnviarVacunas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void tbeTablaVacunasComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tbeTablaVacunasComponentAdded
        
    }//GEN-LAST:event_tbeTablaVacunasComponentAdded

    private void listaVacunatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVacunatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaVacunatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnviarVacunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnviarVacunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnviarVacunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnviarVacunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EnviarVacunas().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EnviarVacunas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(EnviarVacunas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(EnviarVacunas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblSeleccionVacunatorio;
    private javax.swing.JComboBox<String> listaVacunatorios;
    private javax.swing.JTable tbeTablaVacunas;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
