/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

/**
 *
 * @author Geno
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
        dispose();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInmunidadRebanio = new javax.swing.JLabel();
        lblTotalVacunados = new javax.swing.JLabel();
        lblTotalAgendados = new javax.swing.JLabel();
        lblPorcentajeVacunados = new javax.swing.JLabel();
        lblNumeroInmunidadRebanio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNumeroTotalVacunados1 = new javax.swing.JLabel();
        lblNumeroTotalAgendados1 = new javax.swing.JLabel();
        lblNumeroPorcentajeVacunados1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 340));
        setPreferredSize(new java.awt.Dimension(680, 340));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInmunidadRebanio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInmunidadRebanio.setText("Inmunidad de Rebaño:");
        getContentPane().add(lblInmunidadRebanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        lblTotalVacunados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalVacunados.setText("Total Vacunados:");
        getContentPane().add(lblTotalVacunados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        lblTotalAgendados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalAgendados.setText("Total Agendados:");
        getContentPane().add(lblTotalAgendados, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        lblPorcentajeVacunados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPorcentajeVacunados.setText("Porcentaje Vacunados:");
        getContentPane().add(lblPorcentajeVacunados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblNumeroInmunidadRebanio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNumeroInmunidadRebanio.setText("2000000");
        getContentPane().add(lblNumeroInmunidadRebanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 500, -1));

        lblNumeroTotalVacunados1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNumeroTotalVacunados1.setText("2000000");
        getContentPane().add(lblNumeroTotalVacunados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        lblNumeroTotalAgendados1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNumeroTotalAgendados1.setText("2000000");
        getContentPane().add(lblNumeroTotalAgendados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        lblNumeroPorcentajeVacunados1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNumeroPorcentajeVacunados1.setText("2000000");
        getContentPane().add(lblNumeroPorcentajeVacunados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblInmunidadRebanio;
    private javax.swing.JLabel lblNumeroInmunidadRebanio;
    private javax.swing.JLabel lblNumeroPorcentajeVacunados1;
    private javax.swing.JLabel lblNumeroTotalAgendados1;
    private javax.swing.JLabel lblNumeroTotalVacunados1;
    private javax.swing.JLabel lblPorcentajeVacunados;
    private javax.swing.JLabel lblTotalAgendados;
    private javax.swing.JLabel lblTotalVacunados;
    // End of variables declaration//GEN-END:variables
}
