/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Sistema;
import logica.Vacuna;
import logica.Vacuna.TipoVacuna;


public class IngresarVacuna extends javax.swing.JFrame {

    public IngresarVacuna() {
        initComponents();
        dispose();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        lblTipoVacuna = new javax.swing.JLabel();
        lblCantidadDosis = new javax.swing.JLabel();
        lblLaboratorio = new javax.swing.JLabel();
        lblFechaVencimiento = new javax.swing.JLabel();
        txtCantidadDosis = new javax.swing.JTextField();
        txtLaboratorio = new javax.swing.JTextField();
        listaVacunas = new javax.swing.JComboBox<>();
        lblIngresoStockVacunas = new javax.swing.JLabel();
        jdateFechaVencimiento = new org.netbeans.modules.form.InvalidComponent();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblTipoVacuna.setText("Tipo de vacuna:");

        lblCantidadDosis.setText("Cantidad de dosis:");

        lblLaboratorio.setText("Laboratorio:");

        lblFechaVencimiento.setText("Fecha de vencimiento.:");

        listaVacunas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinovac", "Pfizer", "Astrazeneca" }));
        listaVacunas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaVacunasItemStateChanged(evt);
            }
        });
        listaVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVacunasActionPerformed(evt);
            }
        });

        lblIngresoStockVacunas.setText("Ingreso de stock de vacunas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLaboratorio)
                                    .addComponent(lblCantidadDosis)
                                    .addComponent(lblFechaVencimiento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidadDosis)
                                    .addComponent(txtLaboratorio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jdateFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(lblTipoVacuna)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(listaVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblIngresoStockVacunas))
                                .addGap(0, 110, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblIngresoStockVacunas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoVacuna)
                    .addComponent(listaVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDosis)
                    .addComponent(txtCantidadDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLaboratorio)
                    .addComponent(txtLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaVencimiento)
                    .addComponent(jdateFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaVacunasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaVacunasItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaVacunasItemStateChanged

    private void listaVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVacunasActionPerformed
        
    }//GEN-LAST:event_listaVacunasActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
           
        int item=listaVacunas.getSelectedIndex();
        TipoVacuna tipoVacuna=null;
                
        switch (item){
            case 0: tipoVacuna = TipoVacuna.SINOVAC;   break;
            case 1: tipoVacuna = TipoVacuna.PFIZER; break;
            case 2: tipoVacuna = TipoVacuna.ASTRAZENECA; break;
        }
       
        java.util.Date date = new java.util.Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("YYYY-MM-dd");
        String fechaVencimiento=formatoFecha.format(jdateFechaVencimiento.getDate());
        
        String laboratorio="";
        int dosisDisponibles=0;
        String[] fecha = new String[3];
        
        if(!txtCantidadDosis.getText().trim().equalsIgnoreCase("")){
            dosisDisponibles = Integer.parseInt(txtCantidadDosis.getText());
        }
            if(!txtLaboratorio.getText().trim().equalsIgnoreCase("")){
                laboratorio = txtLaboratorio.getText();
            }
                if(!fechaVencimiento.trim().equalsIgnoreCase("")){
                    Vacuna vacuna = new Vacuna(tipoVacuna, fechaVencimiento, dosisDisponibles, laboratorio);
            try {
                Sistema.getInstance().registrarVacunas(vacuna);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IngresarVacuna.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(IngresarVacuna.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(IngresarVacuna.class.getName()).log(Level.SEVERE, null, ex);
            }
                    JOptionPane.showMessageDialog(this, "Se guardó exitosamente");              
                }
        txtCantidadDosis.setText("");
        txtLaboratorio.setText("");
        jdateFechaVencimiento.setCalendar(null);
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarVacuna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel4;
    private org.netbeans.modules.form.InvalidComponent jdateFechaVencimiento;
    private javax.swing.JLabel lblCantidadDosis;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblIngresoStockVacunas;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblTipoVacuna;
    private javax.swing.JComboBox<String> listaVacunas;
    private javax.swing.JTextField txtCantidadDosis;
    private javax.swing.JTextField txtLaboratorio;
    // End of variables declaration//GEN-END:variables
}
