/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Sistema;

/**
 *
 * @author Geno
 */
public class MenuMSP extends javax.swing.JFrame {

    /**
     * Creates new form MenuMSP
     */
    public MenuMSP() {
        initComponents();
        dispose();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_TipoVacuna = new javax.swing.ButtonGroup();
        btnEnviarVacunas = new javax.swing.JButton();
        btnIngresarVacunas = new javax.swing.JButton();
        btnVerEstadisticas = new javax.swing.JButton();
        lblTexto1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        spnRangoSuperior = new javax.swing.JSpinner();
        rbtnSinovac = new javax.swing.JRadioButton();
        rbtnPfizer = new javax.swing.JRadioButton();
        rbtnAstrazeneca = new javax.swing.JRadioButton();
        spnRangoInferior = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        lblDosis = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIngresarRango = new javax.swing.JButton();
        btnActualizarHabilitados = new javax.swing.JButton();
        txtRangoInferior = new javax.swing.JTextField();
        lblTexto3 = new javax.swing.JLabel();
        txtRangoSuperior = new javax.swing.JTextField();
        lblTexto2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 580));
        setPreferredSize(new java.awt.Dimension(1100, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviarVacunas.setText("Enviar Vacunas");
        btnEnviarVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarVacunasActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarVacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, -1, -1));

        btnIngresarVacunas.setText("Ingresar Vacunas");
        btnIngresarVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarVacunasActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarVacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, -1));

        btnVerEstadisticas.setText("Ver Estadisticas");
        btnVerEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        lblTexto1.setText("Las personas comprendidas entre");
        getContentPane().add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Personas habilitadas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 650, 10));

        spnRangoSuperior.setModel(new javax.swing.SpinnerNumberModel(1, 1, 150, 1));
        jPanel1.add(spnRangoSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        buttonGroup_TipoVacuna.add(rbtnSinovac);
        rbtnSinovac.setText("Sinovac");
        rbtnSinovac.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(rbtnSinovac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        buttonGroup_TipoVacuna.add(rbtnPfizer);
        rbtnPfizer.setText("Pfizer");
        jPanel1.add(rbtnPfizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        buttonGroup_TipoVacuna.add(rbtnAstrazeneca);
        rbtnAstrazeneca.setText("Astrazeneca");
        jPanel1.add(rbtnAstrazeneca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        spnRangoInferior.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(spnRangoInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel1.setText("Entre                            y");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 185, -1, -1));

        lblDosis.setText("Dosis:");
        jPanel1.add(lblDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel3.setText("Rango de Edades:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 150, -1, -1));

        jLabel4.setText("Establecer tipo de dosis según edad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnIngresarRango.setText("Ingresar");
        btnIngresarRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarRangoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 120, 30));

        btnActualizarHabilitados.setText("Actualizar");
        btnActualizarHabilitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHabilitadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarHabilitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 120, 30));

        txtRangoInferior.setMinimumSize(new java.awt.Dimension(60, 25));
        txtRangoInferior.setPreferredSize(new java.awt.Dimension(60, 25));
        txtRangoInferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRangoInferiorActionPerformed(evt);
            }
        });
        jPanel1.add(txtRangoInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 35, 30));

        lblTexto3.setText("años.");
        jPanel1.add(lblTexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        txtRangoSuperior.setMinimumSize(new java.awt.Dimension(60, 25));
        txtRangoSuperior.setPreferredSize(new java.awt.Dimension(60, 25));
        txtRangoSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRangoSuperiorActionPerformed(evt);
            }
        });
        jPanel1.add(txtRangoSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 35, 30));

        lblTexto2.setText("y");
        jPanel1.add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 680, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarVacunasActionPerformed
        IngresarVacuna ingresarVacuna = new IngresarVacuna();
        ingresarVacuna.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIngresarVacunasActionPerformed

    private void btnEnviarVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarVacunasActionPerformed
        EnviarVacunas enviarVacunas = null;
        try {
            enviarVacunas = new EnviarVacunas();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
        }
        enviarVacunas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEnviarVacunasActionPerformed

    private void btnVerEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadisticasActionPerformed
        Estadisticas estadisticas = new Estadisticas();
        estadisticas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVerEstadisticasActionPerformed

    private void txtRangoInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRangoInferiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRangoInferiorActionPerformed

    private void txtRangoSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRangoSuperiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRangoSuperiorActionPerformed

    private void btnActualizarHabilitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHabilitadosActionPerformed
        int edadInferior=0;
        int edadSuperior=0;
        
        if (txtRangoInferior.getText().trim().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this,"Digite la edad inferior del rango");
            }
        else{
            try {
                edadInferior = Integer.parseInt(txtRangoInferior.getText());
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this,"El campo debe ser numérico");
            }
            if (txtRangoSuperior.getText().trim().equalsIgnoreCase("")){
                 JOptionPane.showMessageDialog(this,"Digite la edad superior del rango");
            } else {
                try {
                    edadSuperior = Integer.parseInt(txtRangoSuperior.getText());
                } catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this,"El campo debe ser numérico");
                }
                }
            }
        
        if (edadInferior < 0 || edadSuperior < 0){
            JOptionPane.showMessageDialog(this, "El campo debe ser mayor a cero");
        }
        else {
            try {
                boolean actualizar = Sistema.getInstance().actualizarRangoHabilitados(edadInferior, edadSuperior);
                if (actualizar){
                    JOptionPane.showMessageDialog(this, "Se actualizó correctamente");
                    txtRangoInferior.setText("");
                    txtRangoSuperior.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar, verifique los campos");
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnActualizarHabilitadosActionPerformed

    private void btnIngresarRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarRangoActionPerformed
        String tipoVacuna=null;
        int edadInferior = Integer.parseInt(spnRangoInferior.getValue().toString());
        int edadSuperior = Integer.parseInt(spnRangoSuperior.getValue().toString());
        
        if(rbtnSinovac.isSelected()){
            tipoVacuna = "Sinovac";
        } else if (rbtnPfizer.isSelected()){
            tipoVacuna = "Pfizer";            
            } else if (rbtnAstrazeneca.isSelected()){
                tipoVacuna = "Astrazeneca";
                } else {
                JOptionPane.showMessageDialog(this, "Selecciones el tipo de dosis");
            }
        
        try {
            if(Sistema.getInstance().ingresarHabilitados(tipoVacuna, edadInferior, edadSuperior)){
                JOptionPane.showMessageDialog(this, "Se ingresó correctamente");
            } else {
            JOptionPane.showMessageDialog(this, "No se pudo ingresar, verifique los campos");
        }
        }catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MenuMSP.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_btnIngresarRangoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarHabilitados;
    private javax.swing.JButton btnEnviarVacunas;
    private javax.swing.JButton btnIngresarRango;
    private javax.swing.JButton btnIngresarVacunas;
    private javax.swing.JButton btnVerEstadisticas;
    private javax.swing.ButtonGroup buttonGroup_TipoVacuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDosis;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JRadioButton rbtnAstrazeneca;
    private javax.swing.JRadioButton rbtnPfizer;
    private javax.swing.JRadioButton rbtnSinovac;
    private javax.swing.JSpinner spnRangoInferior;
    private javax.swing.JSpinner spnRangoSuperior;
    private javax.swing.JTextField txtRangoInferior;
    private javax.swing.JTextField txtRangoSuperior;
    // End of variables declaration//GEN-END:variables
}
